import nx from '@nx/eslint-plugin';

/**
 * Workspace-wide ESLint flat config.
 *
 * The important part is `@nx/enforce-module-boundaries`: it is what makes the
 * `app -> feature -> shared` import direction a build error rather than a code-review
 * comment. Every project carries a `scope:*` tag in its `project.json`; the constraints below
 * declare, per scope, which other scopes it may import from.
 *
 * When you add a feature library, add its `scope:feature-*` tag here in TWO places:
 *   1. `scope:app`'s `onlyDependOnLibsWithTags` (so the app may route to it), and
 *   2. its own entry, listing the shared scopes it may consume.
 * Feature libraries must never depend on each other — extract to `shared/*` instead.
 */
export default [
  ...nx.configs['flat/base'],
  ...nx.configs['flat/typescript'],
  ...nx.configs['flat/javascript'],
  {
    // `**/public/mockServiceWorker.js` is generated by `npx msw init` — vendored, not authored,
    // and ships its own `/* eslint-disable */` header that this workspace's flat config has
    // nothing to disable, hence the otherwise-harmless "unused eslint-disable directive"
    // warning it would trigger if linted.
    ignores: ['**/dist', '**/out-tsc', '**/vitest.config.*.timestamp*', '**/public/mockServiceWorker.js'],
  },
  {
    files: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx'],
    rules: {
      '@nx/enforce-module-boundaries': [
        'error',
        {
          enforceBuildableLibDependency: true,
          allow: ['^.*/eslint(\\.base)?\\.config\\.[cm]?[jt]s$'],
          depConstraints: [
            {
              sourceTag: 'scope:app',
              onlyDependOnLibsWithTags: [
                'scope:data-access',
                'scope:shared-ui',
                'scope:shared-util',
                'scope:auth',
                'scope:shell',
                'scope:feature-items',
              ],
            },
            {
              // SAMPLE FEATURE — delete this entry along with `libs/feature-items`.
              sourceTag: 'scope:feature-items',
              onlyDependOnLibsWithTags: [
                'scope:data-access',
                'scope:shared-ui',
                'scope:shared-util',
                'scope:auth',
              ],
            },
            {
              sourceTag: 'scope:shell',
              onlyDependOnLibsWithTags: [
                'scope:data-access',
                'scope:shared-ui',
                'scope:shared-util',
                'scope:auth',
              ],
            },
            {
              sourceTag: 'scope:auth',
              onlyDependOnLibsWithTags: ['scope:data-access', 'scope:shared-util'],
            },
            {
              sourceTag: 'scope:data-access',
              onlyDependOnLibsWithTags: ['scope:data-access', 'scope:shared-util'],
            },
            {
              sourceTag: 'scope:shared-ui',
              onlyDependOnLibsWithTags: ['scope:data-access', 'scope:shared-util'],
            },
            {
              sourceTag: 'scope:shared-util',
              onlyDependOnLibsWithTags: ['scope:shared-util'],
            },
          ],
        },
      ],
    },
  },
  {
    files: [
      '**/*.ts',
      '**/*.tsx',
      '**/*.cts',
      '**/*.mts',
      '**/*.js',
      '**/*.jsx',
      '**/*.cjs',
      '**/*.mjs',
    ],
    // Override or add rules here
    rules: {},
  },
];
